name: workiom
description: Workiom - The Easy & Fast Way to Manage Your Team & Data.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Http
  dio: ^4.0.0
  dio_http_cache: ^0.3.0
  pretty_dio_logger: ^1.1.1
  dio_smart_retry: ^1.0.0


  #state management
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0


  #ui
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  pinput: 1.2.0
  date_field: ^3.0.1
  lottie: ^1.4.1
  google_nav_bar: ^5.0.5
  awesome_dialog: ^3.0.2
  country_code_picker: ^2.0.1
  intl_phone_number_input: ^0.7.0+2
  intl_phone_field: ^3.1.0
  shimmer: ^2.0.0
  flutter_svg: ^1.1.6
  animated_snack_bar: ^0.2.1

  #utils
#  flutter_fcm: ^1.0.8
  pull_to_refresh: ^2.0.0
  connectivity: ^3.0.6
  flutter_staggered_animations: ^1.0.0
  simple_animations: 4.0.1
  equatable: ^2.0.3
  package_info_plus: ^1.4.2
  flutter_phoenix: ^1.0.0
  flutter_screenutil: 5.1.0
  easy_localization: ^3.0.0
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  url_launcher: ^6.0.3
  cached_network_image: ^3.0.0
  timeago: ^3.1.0
  file_picker: ^4.1.3
  image_picker: ^0.8.4+11
  readmore: 2.1.0
  expandable: ^5.0.1
  share_plus: ^4.0.4
  flutter_holo_date_picker: ^1.0.1+2
  dropdown_button2: ^1.2.2
  flutter_launcher_icons: ^0.9.2
  flutter_password_strength: ^0.1.6
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  icons_launcher: ^1.1.5
  flutter_lints: ^1.0.4

flutter_icons:
  image_path: 'assets/images/app_icon.png'
  ios: true
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/sound/
    - assets/lottie/


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
        - asset: assets/fonts/Rubik-BlackItalic.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik-BoldItalic.ttf
        - asset: assets/fonts/Rubik-ExtraBold.ttf
        - asset: assets/fonts/Rubik-ExtraBoldItalic.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
        - asset: assets/fonts/Rubik-Light.ttf
        - asset: assets/fonts/Rubik-LightItalic.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-MediumItalic.ttf
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-SemiBold.ttf
        - asset: assets/fonts/Rubik-SemiBoldItalic.ttf
